# app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-stable
  labels:
    app: devops-app
    version: stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-app
      version: stable
  template:
    metadata:
      labels:
        app: devops-app
        version: stable
    spec:
      containers:
        - name: devops-app
          image: devops-app:1.0.0  # stable sürümü
          ports:
            - containerPort: 52000
          env:
            - name: NODE_ENV
              value: "production"
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: PORT
              value: "52000"
            - name: VERSION
              value: "1.0.0"
          volumeMounts:
            - name: app-volume
              mountPath: /app
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          command: ["npm", "start"]
      volumes:
        - name: app-volume
          hostPath:
            path: /mnt/data
