services:
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    networks:
      - devops-network
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge
